apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lostfound-public
spec:
  ingressClassName: nginx
  rules:
    - host: lostfound.com
      http:
        paths:
          - path: /auth/login
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000
          - path: /auth/register
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lostfound-protected
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://api-gateway-svc.default.svc.cluster.local:80/auth-check"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id,X-User-Email,X-User-Role"
spec:
  ingressClassName: nginx
  rules:
    - host: lostfound.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000

          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catalog-svc
                port:
                  number: 3001

          - path: /claims
            pathType: Prefix
            backend:
              service:
                name: claims-svc
                port:
                  number: 3002

          - path: /report
            pathType: Prefix
            backend:
              service:
                name: report-svc
                port:
                  number: 3003

          - path: /profile
            pathType: Prefix
            backend:
              service:
                name: profile-svc
                port:
                  number: 3004

          - path: /feedback
            pathType: Prefix
            backend:
              service:
                name: feedback-svc
                port:
                  number: 3005
