services:
  report-service:
    build: .
    container_name: report-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - CATALOG_SERVICE_URL=http://localhost:3002
      - CLAIMS_SERVICE_URL=http://localhost:3003



