services:
  report-service:
    build: .
    container_name: report-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - CATALOG_SERVICE_URL=http://<CATALOG_EC2_IP>:3002
      - CLAIMS_SERVICE_URL=http://<CLAIMS_EC2_IP>:3003
