services:
  mongo:
    image: mongo:7
    container_name: logs-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - logs-network

  activity-log-service:
    build: .
    container_name: activity-log-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - MONGO_URI=mongodb://mongo:27017/logs-db
    depends_on:
      - mongo
    networks:
      - logs-network

volumes:
  mongo-data:

networks:
  logs-network:
    driver: bridge
