apiVersion: apps/v1

kind: Deployment

metadata:
  name: auth-deployment
  labels:
    app: auth

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth-container
          image: jinn2/lostfound-auth-service:v1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET

            - name: PORT
              value: "3000"

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5