
apiVersion: apps/v1

kind: Deployment

metadata:
  name: report-deployment
  labels:
    app: report

spec:
  replicas: 1

  selector:
    matchLabels:
      app: report

  template:
    metadata:
      labels:
        app: report

    spec:
      containers:
        - name: report-container
          image: jinn2/lostfound-report-service:v1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3003

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: report-secret
                  key: JWT_SECRET

            - name: PORT
              value: "3003"

            - name: CATALOG_SERVICE_URL
              value: "http://catalog-svc:3001"
            - name: CLAIMS_SERVICE_URL
              value: "http://claims-svc:3002"

          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5