  claims-service:
    build: .
    container_name: claims-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/claims-db
      - JWT_SECRET=lost-and-found-secret-key
    depends_on:
      - mongo
    networks:
      - claims-network

volumes:
  mongo-data:

networks:
  claims-network:
    driver: bridge

